name: Docker Image CI

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 15 * * *'
  push:
    paths:
    - 'docker/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: docker build ./docker --file docker/Dockerfile --tag comokit/comokit:latest

    - name: Log in Docker Hub
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Push new container to Docker Hub
      run: docker push comokit/comokit:latest
