# Workflow to install Sphinx ( https://www.sphinx-doc.org/ - Python documentation generator), 
# generate HTML
# and deploy it on a branch linked to Github Pages

name: "CI/CD Doc-string"

on:
  push:
    branches:
      - main
    paths:
      - 'comokit4py/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: "Set up Python"
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: "Install Python Sphinx && dependencies"
        run: |
          pip3 install setuptools
          pip3 install -r base/pre-processing/requirements.txt
          pip3 install -r base/post-processing/requirements.txt
          pip3 install sphinx sphinx-rtd-theme

      - name: "Build Sphinx Doc"
        run: |
          make html

      - name: "Deploy Github Pages"
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/_build/html/
